version: '3.8'

services:
  frontend:
    build:
      context: ../frontend/
      dockerfile: ../frontend/Dockerfile
    volumes:
      - ../frontend/src/bundles:/src/bundles
      - ../frontend/src/bundles-src:/src/bundles-src
    command: ./node_modules/.bin/parcel watch bundles-src/index.js --dist-dir bundles --public-url="./"

  db:
    image: postgres
    env_file:
      - ../backend/src/star_burger/.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: ../backend/
      dockerfile: ../backend/Dockerfile
    volumes:
      - media:/src/media
      - ../backend/src:/src
      - ../frontend/src/bundles:/src/bundles
    restart: always
    depends_on:
      - frontend
      - db
    ports:
      - '8000:8000'
    entrypoint: python manage.py runserver 0.0.0.0:8000

volumes:
  pgdata:
  media:
