version: '3.8'

services:
  front_helper:
    build:
      context: ../frontend/
      dockerfile: ../frontend/Dockerfile
    volumes:
      - frontend:/src/frontend
    entrypoint:  ["sh", "-c", "cp -a /src/bundles/* /src/frontend/"]

  app:
    build:
      context: ../backend/
      dockerfile: ../backend/Dockerfile
    volumes:
      - frontend:/src/frontend
    restart: always
    depends_on:
      front_helper:
        condition: service_completed_successfully
      back_helper:
        condition: service_completed_successfully
    ports:
      - '8000:8000'
    entrypoint: python manage.py runserver 0.0.0.0:8000

volumes:
  frontend:
