# Generated by Django 3.2.15 on 2023-07-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='request_datetime',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего обновления'),
        ),
    ]
