# Generated by Django 3.2.15 on 2023-06-20 12:57

from django.db import migrations, models


def copy_price_to_order(apps, schema_editor):
    OrderProduct = apps.get_model('foodcartapp', 'OrderProduct')
    for orderproduct in OrderProduct.objects.select_related('product').all():
        orderproduct.price = orderproduct.product.price
        orderproduct.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_auto_20230617_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='products_in_order', through='foodcartapp.OrderProduct', to='foodcartapp.Product'),
        ),
        migrations.RunPython(copy_price_to_order),
    ]
