# Generated by Django 3.2.15 on 2023-06-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20230621_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.IntegerField(choices=[(0, 'Наличными'), (1, 'Электронно')], db_index=True, default=0, verbose_name='Способ оплаты'),
        ),
    ]
