# Generated by Django 3.2.15 on 2023-06-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20230622_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Новый'), (1, 'Готовится'), (2, 'Доставляется'), (3, 'Выполнен')], db_index=True, default=0, verbose_name='Статус'),
        ),
    ]
