# Generated by Django 3.2.15 on 2023-07-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_alter_order_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.IntegerField(choices=[(0, 'Наличными'), (1, 'Электронно'), (2, 'Не указан')], db_index=True, default=0, verbose_name='Способ оплаты'),
        ),
    ]
