# Generated by Django 3.2.15 on 2023-07-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_alter_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.IntegerField(choices=[(0, 'Наличными'), (1, 'Электронно'), (2, 'Не указан')], db_index=True, default=2, verbose_name='Способ оплаты'),
        ),
    ]
